csiDriver:
  name: "org.democratic-csi.truenas-nfs"

storageClasses:
  - name: truenas-nfs
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - nfsvers=4
      - noatime

volumeSnapshotClasses:
  - name: truenas-nfs
    parameters:
      detachedSnapshots: 'true'

controller:
  driver:
    image:
      tag: next

node:
  hostPID: true
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

driver:
  config:
    driver: freenas-api-nfs
    httpConnection:
      allowInsecure: true
      apiKey: $TRUENAS_API_KEY
      host: 192.168.86.109
      port: 80
      protocol: http
    instance_id: null
    nfs:
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareAlldirs: false
      shareAllowedNetworks:
        - 192.168.86.147
        - 192.168.86.170
        - 192.168.86.27
      shareHost: 192.168.86.109
      shareMapallGroup: kubernetes
      shareMapallUser: kubernetes
    zfs:
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetParentName: Datapool1/Kubernetes/nfs/volumes
      datasetPermissionsGroup: 3001
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 3001
      detachedSnapshotsDatasetParentName: Datapool1/Kubernetes/nfs/snapshots
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"