apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcharr
  namespace: arr
  labels:
    app.kubernetes.io/name: fetcharr
    app.kubernetes.io/part-of: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fetcharr
      app.kubernetes.io/part-of: arr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fetcharr
        app.kubernetes.io/part-of: arr
    spec:
      containers:
        - name: fetcharr
          image: ghcr.io/fetcharr/fetcharr:0.1.16
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /config
              name: config
          envFrom:
            - secretRef:
                name: fetcharr-secrets
                optional: false
          env:
            - name: TZ
              value: "Europe/Stockholm"
      volumes:
        - name: config
          configMap:
            name: fetcharr