apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/component: planning
data:
  ALLOW_SIGNUP: "false"
  TZ: Europe/Stockholm
  BASE_URL: https://recept.albinmedoc.se

  DB_ENGINE: postgres
  POSTGRES_SERVER: postgres.postgres.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: mealie
  POSTGRES_USER: mealie

  OIDC_AUTH_ENABLED: "true"
  OIDC_PROVIDER_NAME: Authentik
  OIDC_CONFIGURATION_URL: https://auth.albinmedoc.se/application/o/mealie/.well-known/openid-configuration
  OIDC_SIGNUP_ENABLED: "true"
  OIDC_USER_GROUP: Mealie users
  OIDC_ADMIN_GROUP: Mealie admins
  OIDC_AUTO_REDIRECT: "true"
  OIDC_SCOPES_OVERRIDE: openid profile email groups mealie
