apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: workflow-automation
data:
  N8N_PROTOCOL: https
  N8N_PORT: "5678"
  N8N_HOST: "n8n.albinmedoc.se"
  WEBHOOK_URL: "https://n8n.albinmedoc.se"
  N8N_PROXY_HOPS: "1"
  GENERIC_TIMEZONE: Europe/Stockholm
  TZ: Europe/Stockholm
  N8N_RUNNERS_ENABLED: "true"
  N8N_HIRING_BANNER_ENABLED: "false"
  QUEUE_HEALTH_CHECK_ACTIVE: "true"
  N8N_DEFAULT_BINARY_DATA_MODE: filesystem
  N8N_BINARY_DATA_STORAGE_PATH: /home/node/.n8n-files
  N8N_RESTRICT_FILE_ACCESS_TO : /home/node/.n8n-files;/tmp
  NODES_EXCLUDE: "[]"
