apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: imposter
  namespace: imposter
  labels:
    app.kubernetes.io/name: imposter
    app.kubernetes.io/component: ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`imposter.flexflix.top`)
      kind: Rule
      services:
        - name: imposter
          port: 3000
      middlewares:
        - name: authentik
          namespace: authentik
