
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dbgate
  namespace: dbgate
  labels:
    app.kubernetes.io/name: dbgate
    app.kubernetes.io/component: management
    app.kubernetes.io/managed-by: kubectl
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`db.albinmedoc.se`)
      kind: Rule
      services:
        - name: dbgate
          port: 3000
      middlewares:
        - name: local-network
          namespace: traefik