---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-secrets
  namespace: traefik
spec:
  encryptedData:
    CF_API_EMAIL: AgCaPyMq4OBdgj7jMm6pV7VgaKdMA70hecJUTWs4G/xhFqHkZDki0PXhXwQ85i2J562KyTijFN/wODkbjqoZ/MXlpPGWdRawQ6lVO+L7Jxya3G0n8Z58HoSzSricOxpjQwslmeZb7t/zR7D5ZLvxmmDlxQZ8FG+dyp5fMoNoceWZP911BJEcDtGNiUJu2t/W1/+mIRACdzNJNrusve73PS6oIogZk6YU6bgZ3jfrSBghiv+tuSIQeaZVzUl6H2uihw4z9+QNk2rf+U5VWUyKZabfL4rsxCxKQykuO7FpG0BOup4W/UaNzNetKrxLBqSuMxvLWqdPCHavoQ2jh2bJXtDCc6wOhBV/14vfelf0YvtByBY358061+SH5DmFXb/DASC4i6e0SMKWSNO8+N7Fak/bMgluZ1+kDJnOwjYxW5v+XWEWUaRZltkFOE0h0aqXoyRyL7jPFWj9iBu5bmessM4RbQcyMeluJbsUFA4uGodIwtwOy9ReSDThzWnsQ1bciF3hjDLTpWTiFGOX2oNdoMdNce7nUTF1sMkZfhe3dcdBfovtoqgfbGl43s3SjAinZet2C1vDZxcTsX2IL9jG9RV2gFsKBvHnH5WQ+eO3Ry39QZQy5tZtLojheFxis0p5WMpVwCEFoVv7pvElj5Z/vxjI/LrANYihVpGtehqDz4ec++dCr9qWO6Rpuz69vyzsL/LvmX1oOLly8t+xT50ozhDyiVrHA9k=
    CF_DNS_API_TOKEN: AgB3S63jdg82Bjocax3t9JFAulHx938EELg72Zd3zAtjAA4MU2aAooJ8ybrchQ3Ov8BnHDfARF7qiYobQbvaGkpjxaGnkT0OvYWFcdHCI7acD6Oi35lSRQ9tJ/2yuKwXdKfuCWLSWOzdp90X3ZQqfdvURSBmszzW1kCP2itYRQ96+0mkXVmwqAws1Bkz4W+v0f5NVbOKU03z1dpuMoIt3sw+EoiXi8BsrfROQfCNNhREu71eVK1zfgjeSPrCyGVQut3fhyNNVvKIFC+oK8fYuBdaKmbGo8JpO+o8Wf8DiHUH52uKiQj+1fw4s54MvbWrndgQ92a73hNjTOrnd6wCCC6GG7kzaXBeFROc+GiCdXCCWRMMRX/Tgpue8FZnseKQZ9rFOH3COvuhrSPLnkCw81l0VEZqjRF32kbxg3I/wat0L+spgnjXnhONEyNt8h4nqTKqse8X38ZfxicBYnAxdN3lcItZqjC6pgD0q18Ms3/ZeIURmkcyKWgrd4gIO8f7aBHo02+aF2I4af/WUnz6yLfKTlS2BlHUdA1dN729/3NCabGzd8r5WpHDvkRPGWmTiq4YqmVi/JM7BQbPzfCxij7pQs5zU77lsv18+uqyQUGp1IU6rZl/HnVYNMfgrfD9j/u+HMfwdd+Jw6ByALwXQIfHyAymvwzzD+VVlXsbv+4LgpfDOYPlRdkUlEFZ7/+jCKQx2ooEdtm+Cd3qWCFp0mhI5sP8IJW74rERlpDtON4JmKhDg8PsaYqX
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: configuration
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/name: traefik
      name: traefik-secrets
      namespace: traefik
