apiVersion: v1
kind: ConfigMap
metadata:
  name: atm10-config
  namespace: minecraft-atm10
  labels:
    app.kubernetes.io/name: minecraft-atm10
    app.kubernetes.io/component: configuration
data:
  EULA: "TRUE"
  MODPACK_PLATFORM: "AUTO_CURSEFORGE"
  CF_SLUG: "all-the-mods-10"
  MEMORY: "8G"
  MAX_MEMORY: "10G"
  USE_AIKAR_FLAGS: "true"
  ENABLE_ROLLING_LOGS: "true"
  TZ: "Europe/Stockholm"
  DIFFICULTY: "normal"
  MAX_PLAYERS: "20"
  VIEW_DISTANCE: "10"
  SIMULATION_DISTANCE: "10"
  ALLOW_FLIGHT: "TRUE"
  SPAWN_PROTECTION: "0"
