apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-rest
  namespace: redis-rest
  labels:
    app.kubernetes.io/name: redis-rest
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-rest
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-rest
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: redis-rest
          image: hiett/serverless-redis-http:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: redis-rest-secrets
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
