apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: plex-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plex-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9594"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: plex-exporter
          image: ghcr.io/axsuul/plex-media-server-exporter:2.1.0
          ports:
            - containerPort: 9594
              name: metrics
              protocol: TCP
          envFrom:
            - secretRef:
                name: plex-exporter-secrets
                optional: false
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
