apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bedrock
  namespace: minecraft-bedrock
  labels:
    app.kubernetes.io/name: minecraft-bedrock
    app.kubernetes.io/component: game-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bedrock.flexflix.top`)
      kind: Rule
      services:
        - name: bedrock
          port: bluemap