---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: configarr
  namespace: arr
spec:
  encryptedData:
    secrets.yml: AgCAaSpGenu7iE1Cd6RHuy0OYutW8iS8YQmTe/Qnmu8xsDk3tOxEHoRStfZqj0u0piK0yoVA7XfTY744dugefl+ZLWUTRf+/94TA389/zoJrpWvr8/KbfuRHNKTfO6oGzBmh2JRSKeBdgb9iYf64eqKZX/3IuFTewyrB1o+1vw/1xB/0tKx7BMWGqvyWsugiIeVTQKYoDLgYa+cPoA4U81IxDvM4Nf4RVx3hI4pFhauy3AaLV4m1q/tB+0zjWzU98mppt5UwVAKzfj1MlqWASIEAyRbYiJXdSywpVaC5+LvhKlk2Z3rxo2Tz/S2csnFV2hDkQaV3jWKMgP8vD64Ae8EJknL1EbYwjJR49VB1l6sFUOC8EcLTTmc1GCY31JtDlkCOcV2ZZ+Da3x4Q98LY2xyX/8eM2UPRRKskz0Z4HmKAk3SKa6h4PhTIUZI8w2Y4B4ojSRYXzMuRZZ7T9pAeMVxUcjAIfpLV5P01fYUpPRmDXNba8C04UAONkz/l5xgM43Plou9cUIa+eL6vqQVfgC2IkpSXCgFURwDNzZ1gogLHW5p2U1foT1uX8CE74FVv+rZjTHk9EV4X5gs5LdtSx1TNfco71p4r+Zk9As3ZDI8IvQzJ/BQzB8kA5fzpKQL9Doj1aaIW39x16TDbF3hqj7W7Ux2UO14DF9e9K6zFxMOxH0mHLXO+Zhs2r884qNTEDzGYHIP2vBsfbuygoPRclDmaaunqAK4QX1bnhUz2+iWX8EVT7ywJBvOxLZMvorQe5TXHUgic34rGng+Xcnn8ilHIop9hZO0oq6tB+7fK9l/QbEjOLYmFVVpMViOy0fuR/VLQzCera84=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/name: configarr
        app.kubernetes.io/part-of: arr
      name: configarr
      namespace: arr
    type: Opaque
