apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nzbdav
  namespace: arr
  labels:
    app.kubernetes.io/name: nzbdav
    app.kubernetes.io/part-of: arr
    app.kubernetes.io/managed-by: kubectl
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nzbdav.flexflix.top`)
      kind: Rule
      services:
        - name: nzbdav
          port: 3000
      middlewares:
        - name: local-network
          namespace: traefik
        - name: authentik
          namespace: authentik