apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: photoprism-minnen
  labels:
    app.kubernetes.io/name: photoprism
    app.kubernetes.io/instance: minnen
    app.kubernetes.io/component: photo-manager
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: photoprism
      app.kubernetes.io/instance: minnen
      app.kubernetes.io/component: photo-manager
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: photoprism
        app.kubernetes.io/instance: minnen
        app.kubernetes.io/component: photo-manager
        app.kubernetes.io/managed-by: kubectl
    spec:
      containers:
        - name: photoprism
          image: photoprism/photoprism:251130
          env:
            - name: PHOTOPRISM_SITE_URL
              value: https://minnen.albinmedoc.se
            - name: PHOTOPRISM_DISABLE_CHOWN
              value: "true"
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: mysql
            - name: PHOTOPRISM_SITE_CAPTION
              value: "Minnen"
            - name: PHOTOPRISM_AUTH_MODE
              value: "public"
            - name: PHOTOPRISM_DISABLE_SETTINGS
              value: "true"
            - name: PHOTOPRISM_UPLOAD_NSFW
              value: "true"
            - name: PHOTOPRISM_DISABLE_VECTORS
              value: "false"
            - name: PHOTOPRISM_HTTP_HOST
              value: 0.0.0.0
            - name: PHOTOPRISM_HTTP_PORT
              value: "2342"
          # Load database environment variables from secret
          envFrom:
            - secretRef:
                name: photoprism-secrets
                optional: false
          ports:
            - containerPort: 2342
              name: http
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /photoprism/originals
              name: originals
            - mountPath: /photoprism/storage
              name: storage
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: http
      volumes:
        - name: originals
          nfs:
            path: /mnt/Datapool1/Data/Minnen
            server: 192.168.86.109
        - name: storage
          persistentVolumeClaim:
            claimName: photoprism