apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-router
  namespace: minecraft-router
  labels:
    app.kubernetes.io/name: minecraft-router
    app.kubernetes.io/component: router
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-router
      app.kubernetes.io/component: router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-router
        app.kubernetes.io/component: router
    spec:
      serviceAccountName: minecraft-router
      containers:
        - name: mc-router
          image: itzg/mc-router:latest
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
          env:
            - name: IN_KUBE_CLUSTER
              value: "true"
            - name: KUBE_NAMESPACE
              value: ""
            - name: PORT
              value: "25565"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
