apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: convertx
  namespace: convertx
  labels:
    app.kubernetes.io/name: convertx
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: kubectl
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`convert.flexflix.top`)
      kind: Rule
      services:
        - name: convertx
          port: 3000
      middlewares:
        - name: authentik
          namespace: authentik
