apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: immich-minnen
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: minnen
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minnen.albinmedoc.se`)
      kind: Rule
      services:
        - name: immich
          port: 2283