apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich-minnen
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: minnen
data:
  IMMICH_PORT: "2283"
  DB_STORAGE_TYPE: HDD
  TZ: "Europe/Stockholm"